# -*- coding: utf-8 -*-
#
# Programación Test documentation build configuration file, created by
# sphinx-quickstart on Sat Jan 30 21:58:48 2010.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.append(os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    #'sphinx.ext.pngmath',
    'sphinx.ext.jsmath',
]

templates_path = ['_templates']

source_suffix = '.rst'
master_doc = 'index' # The master toctree document.

project = u'Programación 1-2010'
copyright = u'2010, Roberto Bonvallet'
version = '' # The short X.Y version.
release = '' # The full version, including alpha/beta/rc tags.
language = 'es'

# List of documents that shouldn't be included in the build.
unused_docs = ['disqus']

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

#default_role = None  # for `text`

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ---------------------------------------------------

html_theme = 'sphinxdoc'
html_theme_options = {
    'nosidebar': True,
}
html_title = u'Programación, 1er semestre de 2010'
html_short_title = u'Programación 1-2010'
#html_logo = None
#html_favicon = None
html_style = 'progra.css'

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
html_use_modindex = False

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# Output file base name for HTML help builder.
htmlhelp_basename = 'progra-utfsm-2010-1'

# -- Options for LaTeX output --------------------------------------------------

latex_paper_size = 'letter'
#latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'progra.tex', u'Programación 1er semestre 2010',
   u'Roberto Bonvallet', 'manual'),
]

latex_elements = {
    'fontpkg': '\\usepackage{mathpazo}',
    'pointsize': '12pt',
    #'preamble': '\\usepackage[spanish]{babel} \selectlanguage{spanish}',
}

#latex_logo = None
#latex_use_parts = False   # parts instead of chapters in manual
#latex_preamble = ''
#latex_appendices = []   # docs to append as appendix to all manuals

# If false, no module index is generated.
latex_use_modindex = False

highlight_language = 'pascal'

jsmath_path = 'jsMath/easy/load.js'

